"""initial schema

Revision ID: 27fcfaadbc1c
Revises: 
Create Date: 2026-05-25 16:49:07.629984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '27fcfaadbc1c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('pickup_location', sa.Text(), nullable=True),
    sa.Column('default_priority', sa.Enum('speed', 'price', 'balanced', name='defaultpriority'), nullable=False),
    sa.Column('default_shipping_preference', sa.Enum('pickup_only', 'shipping_only', 'both', name='shippingpreference'), nullable=False),
    sa.Column('default_markdown_percent', sa.Float(), nullable=False),
    sa.Column('default_markdown_days', sa.Integer(), nullable=False),
    sa.Column('default_floor_price', sa.Float(), nullable=False),
    sa.Column('notification_email', sa.String(length=255), nullable=True),
    sa.Column('pushover_key', sa.String(length=255), nullable=True),
    sa.Column('ebay_oauth_token', sa.Text(), nullable=True),
    sa.Column('etsy_access_token', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=255), nullable=True),
    sa.Column('condition', sa.Enum('new', 'like_new', 'good', 'fair', 'poor', name='condition'), nullable=True),
    sa.Column('condition_description', sa.Text(), nullable=True),
    sa.Column('keywords', sa.JSON(), nullable=True),
    sa.Column('dimensions', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('draft', 'active', 'sold', 'archived', name='listingstatus'), nullable=False),
    sa.Column('priority', sa.Enum('speed', 'price', 'balanced', name='priority'), nullable=False),
    sa.Column('shipping_preference', sa.Enum('pickup_only', 'shipping_only', 'both', name='shippingpreference'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('quantity_available', sa.Integer(), nullable=False),
    sa.Column('quantity_sold', sa.Integer(), nullable=False),
    sa.Column('photos', sa.JSON(), nullable=True),
    sa.Column('ai_analysis', sa.JSON(), nullable=True),
    sa.Column('ebay_listing_id', sa.String(length=255), nullable=True),
    sa.Column('etsy_listing_id', sa.String(length=255), nullable=True),
    sa.Column('markdown_percent', sa.Float(), nullable=True),
    sa.Column('markdown_days', sa.Integer(), nullable=True),
    sa.Column('floor_price', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('listed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sold_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('notification_type', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platform_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('facebook', 'kijiji', 'ebay', 'craigslist', 'etsy', name='platform'), nullable=False),
    sa.Column('platform_listing_id', sa.String(length=255), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('list_price', sa.Float(), nullable=False),
    sa.Column('platform_fee', sa.Float(), nullable=False),
    sa.Column('shipping_cost', sa.Float(), nullable=False),
    sa.Column('net_profit', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('active', 'sold', 'archived', name='platformlistingstatus'), nullable=False),
    sa.Column('listed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sold_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('facebook', 'kijiji', 'ebay', 'craigslist', 'etsy', name='platform'), nullable=True),
    sa.Column('old_price', sa.Float(), nullable=False),
    sa.Column('new_price', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('price_history')
    op.drop_table('platform_listings')
    op.drop_table('notification_logs')
    op.drop_table('listings')
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
